version: '3.5'
services:
  config-service:
    container_name: config-service
    build: config-service
    ports:
      - 8001:8001

  registry:
    container_name: registry
    restart: always
    build: registry
    ports:
      - 8761:8761
    depends_on:
      - config-service

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - 8989:8989
    depends_on:
      - config-service
      - registry
  rate-service:
    container_name: rate-service
    restart: on-failure
    build: rate-service
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - registry

  subscription-service:
    container_name: subscription-service
    restart: on-failure
    build: subscription-service
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - registry

  notification-service:
    container_name: notification-service
    restart: on-failure
    build: notification-service
    ports:
      - 9999:9999
    depends_on:
      - config-service
      - registry

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - config-service
      - registry
#    network_mode: "host"